(defun sumOfBiggerTwo (a b c)
  (cond ((and (>= (+ a b) (+ a c)) (>= (+ a b) (+ b c))) (+ a b))
        ((and (>= (+ a c) (+ a b)) (>= (+ a c) (+ b c))) (+ a c))
        (t (+ b c))
  )
)

;; (setq a (sumOfBiggerTwo 1 2 3))
(write (sumOfBiggerTwo 1 2 3))
(print (sumOfBiggerTwo 1 2 3))
;; (sumOfBiggerTwo 1 1 1)
;; (sumOfBiggerTwo 1 2 2)
;; (sumOfBiggerTwo 1 1 2)
;; (sumOfBiggerTwo 1 4 3)